### ISSUE TITLE
Having the slideshow initially hidden

### ISSUE THREAD

**Issue by faridjame** [noreiller/bootstrap-modal-carousel#12]
Is it possible to have the carousel initially hidden and just display it within the modal after a button/link is clicked? 

I tried setting the display to none for the carousel, but the modal fails to show it if the carousel is initially hidden. 

Thanks

**Comment by saffront** [comment]
Use this bit of jquery to solve your issue:

```
$('#myModal').on('shown.bs.modal', function () {
      $('#myCarousel').removeClass('hidden');
    })

    $('#myModal').on('hidden.bs.modal', function () {
      $('#myCarousel').addClass('hidden');
    })
```
