### ISSUE TITLE
bower.json outdated

### ISSUE THREAD

**Issue by itbra** [noreiller/bootstrap-modal-carousel#20]
Hi, i am working to set up an assets management environment including your plugin. Installing it via bower install works. However, your bower.json file is outdated and the reason for grunt to fire the error Fatal error: Can’t detect main file for "bootstrap-modal-carousel" component. You should explicitly define it via bower_concat’s mainFiles option. See Readme for details.`
Checking your bower.json file i see under `"main":`
```
"docs/css/bootstrap-modal-fullscreen.css",
"docs/css/bootstrap-carousel-fit.css",
"docs/js/bootstrap-carousel-fit.js",
"docs/js/bootstrap-modal-local.js",
"docs/js/bootstrap-modal-fullscreen.js",
"docs/js/bootstrap-modal-carousel.js"
```
This does not reflect your current repo setup. There is no such directory `docs` containing these assets. Bower retrieves this structure:
```
"less/carousel-fit.less",
"less/modal-fullscreen.less",
"js/carousel-fit.js",
"js/modal-carousel.js",
"js/modal-local.js",
"templates/...."
```
This is obviously not what is defined in bower.json. The script files deployed are also not prefixed with `bootstrap-` and - most important thing - the `modal-fullscreen.js` file is missing at all.

Would you please fix that soon?

**Comment by noreiller** [comment]
Hi, thanks for reporting my mistake. I just updated the bower informations with the right libs.

**Comment by itbra** [comment]
You're welcome. Please tell me, what happened to `modal-fullscreen.js`?

**Comment by noreiller** [comment]
Bower is just a representation of the packaged lib. If you want the source libs, ``modal-fulscreen.js`` in the ``src/js`` folder, you have to install the package as a git repo (see http://bower.io/#install-packages).

**Comment by itbra** [comment]
This is infact what i did when i encountered the first issue for which i opened this issue report. But, check the src folder yourself and see that there is no modal-fullscreen.js file in there. So bower won't check it out at all no matter which way i ask it to install your repo. If the file isn't there at all, it won't find it neither way.

**Comment by noreiller** [comment]
The ``modal-fullscreen.js`` is part of 1.x version and the last bower version is 2.0.1.
The new version supports the last version of bootstrap and the new HTML markup of the modal was easier to manipulate in CSS so ``modal-fullscreen.js`` became useless.
Which version do you use in your project ?

**Comment by itbra** [comment]
I switched over to the latest version. However, before i started to set up my assets management environment via bower i always downloaded the *.min.js file from your repo did not watch which files it had merged.

**Comment by itbra** [comment]
I have to come back to the bower.json issue. I tried to fetch your updated plugin via bower update first and after this has not worked via bower install. However, it always fetches the outdated version. I guess you should update the release number not only in bower.json but probably also in package.json. As you can see you the plugin reports to be v2.0.0. Mabe this is why bower does not load the package with the latest bower.json.

**Comment by noreiller** [comment]
I add to create a new tag for this version. The tags are now updated.
