### ISSUE TITLE
Video continues playing event after I close the Modal

### ISSUE THREAD

**Issue by cshirish** [noreiller/bootstrap-modal-carousel#21]
Hi,

I have embedded a YouTube Video inside the Modal, when I click on close the Video still continues to play. I want to video to stop playing when I close the modal and show the content on open. 

Please help. 

Thank you,
Shirish

**Comment by noreiller** [comment]
Hi, the behavior of the close button of the modal, provided by Twitter Bootstrap (see http://getbootstrap.com/javascript/#modals-methods) is to hide the modal.
So, if you want to stop the video playback, you have multiple solutions:

1. Fill the content of the modal on the fly, and remove it when the "hidden.bs.modal" event is triggered
2. Use the Youtube API https://developers.google.com/youtube/js_api_reference

**Comment by SpenMillard** [comment]
Hello there,

This is also occurs if Vimeo is embedded - do you know of a similar fix?

Many thanks,

Spencer

**Comment by noreiller** [comment]
Hi, as I answered it to @cshirish, you have to remove the video from your modal when you close it. Or you can use the Vimeo API https://developer.vimeo.com/player/js-api

**Comment by SpenMillard** [comment]
Hi Noreiller,

Will do, thanks for getting back to me. I have since found a lot of articles regarding this problem with Bootstrap Modal, so will likely get a solution amongst them.

Thanks again,

Spen
