### ISSUE TITLE
The partials are not working

### ISSUE THREAD

**Issue by greyceamorim** [noreiller/bootstrap-modal-carousel#22]
I downloaded, I "bowered" the dependences and the partials dont work :(

**Comment by noreiller** [comment]
Hi, what do you mean with "partials" please ?
If you open the dist/*.html files in a browser, does it work ?

**Comment by greyceamorim** [comment]
Hi, thanks for answered me.

I open the dist/*.html files, but dont load the partials. I didnt understand if I have to re write them in a one whole file html. Or if I open for example the index.html in a browser and should open the header, body and footer.

I dont know if I explained very well, my English is not great. But I really liked of the modal caurosel and I would like to know how use it.


When I open the index.html, it appear without style(css), jquery, and the codes: /'{{> partials/header data.index}}/'  instead load the header.

Sorry I hope I could explain it

**Comment by noreiller** [comment]
It seems you opened the files contained in the "src" folder.

**Comment by greyceamorim** [comment]
Yes, exactly. Should I open in a different way? Im sorry, I m new on it.

**Comment by noreiller** [comment]
The "dist" folder is what you see on http://noreiller.github.com/bootstrap-modal-carousel so can open the "index.html" file and navigate through the pages and inspire yourself for you own use.

**Comment by greyceamorim** [comment]
Thanks a lot @noreiller!
Just one more question, how do you use the "{{> partials/header data.index}}" and transform it in a whole file? 
Is it a technology or a language for it?

**Comment by noreiller** [comment]
It's a handlebar.js (http://handlebarsjs.com/) feature I use with the *grunt-template* package. You can see how I configure it in https://github.com/noreiller/bootstrap-modal-carousel/blob/master/Gruntfile.js#L71:L88 .
If your issue is resolved, please close it. 
I hope you will manage to use the Modal Carousel plugin, and if you don't, you can open your issues here.

**Comment by greyceamorim** [comment]
Thanks a lot @noreiller!
