### ISSUE TITLE
Event detach.bs.local and replaced.bs.local of Modal-local not work?

### ISSUE THREAD

**Issue by HBinhCT** [noreiller/bootstrap-modal-carousel#26]
I read [here](https://noreiller.github.io/bootstrap-modal-carousel/modal-local.html#events) and see Modal-local have 4 event type: detach.bs.local, detached.bs.local, replace.bs.local and replaced.bs.local.
But in my code for testing, only detached.bs.local and replace.bs.local worked with alert.
You can see here: https://jsfiddle.net/cr2ohy9v/
Sorry for my English not good. Thank you.

**Comment by noreiller** [comment]
Hi, the events are triggered on the carousel. So in your example, you can listen the events with:

```
$('#myCarousel').on('detach.bs.local', function() {
	alert('detach.bs.local');
});
$('#myCarousel').on('detached.bs.local', function() {
	alert('detached.bs.local');
});
$('#myCarousel').on('replace.bs.local', function() {
	alert('replace.bs.local');
});
$('#myCarousel').on('replaced.bs.local', function() {
	alert('replaced.bs.local');
});
```

**Comment by HBinhCT** [comment]
It worked. Thank you very much!
